name: woman_safety
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies ellam nammal evide anu type cheyya
#this line .we should keep two space from line
#ok 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shake: ^1.0.0
  permission_handler: ^7.1.0
  flutter_phone_direct_caller: ^2.0.0

  sms_maintained: ^0.2.5
  geolocator: ^7.0.3
  telephony: ^0.1.2
  lottie: ^1.0.1
  fluttertoast: ^8.0.6
  sqflite: ^1.3.0
  path_provider: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
#this is assets all images json files and video song all files are added hear
  assets:
    - assets/alert.json
    - assets/womens.json
    - assets/town.png
    - assets/shake.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 
